apiVersion: batch/v1
kind: CronJob
metadata:
  name: compounder
spec:
  schedule: "*/5 * * * *"  # Run every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: compounder
            image: compounder:latest
          restartPolicy: OnFailure